### ISSUE TITLE
Vehicle Lifecycle Demo - Manufacturing App does not startup

### ISSUE THREAD

**Issue by DennisM330** [hyperledger/composer-sample-applications#103]
On MacOS Sierra 10.12.6, the latest version of the vehicle lifecycle demo with IoT and an Insurance company, does not startup. Investigating further, the MFG app cannot start due to the port number already being in use. It does not try to use port 6001, and instead tries 6002, which is in use by the VDA app. The install.sh script expects the mfg app to be at port 6001. I hardcoded in the app.js to use port 6001 instead of returning to value from cfenv.

**Comment by awjh-ibm** [comment]
Hello @DennisM330, 
This repo is not for the IoT example and is instead just contains the more basic demo. The repository containing the IoT example can be found at https://github.com/IBM-Blockchain/hotwheels. Please could you raise the issue again there?
