### ISSUE TITLE
Vehicle Lifecycle app - Builder Dashboard no longer shows orders

### ISSUE THREAD

**Issue by dconroy** [hyperledger/composer-sample-applications#113]
Were there any changes to underlying code that now breaks this demo?

Orders no longer show up in builder dashboard or in the RMV window

https://imgur.com/a/Wm0Vo

**Comment by dconroy** [comment]
I think it may be a problem with the composer connector npm package

https://www.npmjs.com/package/composer-connector-hlfv1


In node red I can see the message sent from the car builder to the manufacturer, but it errors 

"Error: creating resource error Failed to load connector module "composer-connector-hlfv1" for connection type "hlfv1". Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier-Unexpected identifier"

**Comment by sstone1** [comment]
@dconroy some ES7 code slipped into the Node-RED nodes, but the official Docker image for Node-RED does not use Node.js 8 yet. I've spoken to the Node-RED lead who's going to fix that, but in the short term I've built and published my own image and updated the scripts to use that. Can you pull down the latest changes and try again?

**Comment by dconroy** [comment]
works, thank you
