### ISSUE TITLE
Vehicle-Manufacture-car-builder docker image for 0.0.7 not built

### ISSUE THREAD

**Issue by rmiroballi** [hyperledger/composer-sample-applications#128]
When running the vehicle manufacture demo, the car builder application fails with
> vehicle-manufacture-car-builder@0.0.6 start: `node app.js`
> ...
> Error: Configuration property "restServer" is not defined

The version pulled by docker is 'latest' which seems to be 0.0.6 per the error message.

**Comment by davidkel** [comment]
This should now be fixed, closing.
