### ISSUE TITLE
Demo will not run with Fabric Version 1.0.4 (hlfv1)

### ISSUE THREAD

**Issue by rmiroballi** [hyperledger/composer-sample-applications#129]
When the FABRIC_VERSION environment variable is set to hlfv1, the below error happens.
It does not happen when running with hlfv11 or when the FABRIC_VERSION is not set.

*The hlfv1 version of the demo DOES NOT set the FABRIC_VERSION to hlfv1, so it runs as hlfv11.*

```
# Submit the setup transaction.
docker run \
  --rm \
  --network composer_default \
  -v $(pwd)/.vld-card-store:/home/composer/.composer \
  hyperledger/composer-cli:0.16.5 \
  transaction submit -c admin@vehicle-manufacture-network -d '{"$class": "org.acme.vehicle_network.SetupDemo"}'
pwd
Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Collection with ID '$sysdata' does not exist)
Command failed
```

**Comment by frbrkoala** [comment]
Tried to downgrade to 1.0.3, got the same error. Seems like the problem somewhere else. Downgrading composer to v0.16.2 didn't help ether.

**Comment by davidkel** [comment]
HLF v1.0 and Composer 0.16 are old and have now further development being done. The demo was moved in line with supporting HLF V1.1 and equivalent version of composer and support for the demo running on HLF v1.0 was dropped.
