### ISSUE TITLE
Letters of Credit loading page issue

### ISSUE THREAD

**Issue by guangyingyuan** [hyperledger/composer-sample-applications#150]
Hi ,
I launch the  "Letters of Credit" sample in the master. My nodejs version is  v8.11.3
.When  I tried to open  http://myip:6001/alice,I alwayse show the loading in the page.
![blockchain](https://user-images.githubusercontent.com/39292595/42419285-40503d0e-82e4-11e8-9a75-0cfad1053e25.png)
Can anyone know this is a known issue or something I miss?

**Comment by lulinglingcufe** [comment]
Maybe you should wait for some time. This also happened to me. But then I try to start  composer-rest-server on my sever (not on docker). And then I can see the pages when I start hyperledger/letters-of-credit:latest on docker .

I suggest you first make sure  http://localhost:3000/explorer/ is normally connected. Hope you run the app successfully！

![default](https://user-images.githubusercontent.com/17868127/43569925-9b4d7de4-966b-11e8-9471-f1164d7ccccd.png)

![default](https://user-images.githubusercontent.com/17868127/43569940-a8a34456-966b-11e8-939e-8237179f36cf.png)

**Comment by lulinglingcufe** [comment]
我一开始也是遇到这样的情况。感觉主要先确保 http://localhost:3000/explorer/是可用的。我的情况是 composer-rest-server cli 工具都已经在服务器上部署过，直接启动 composer-rest-server来启动 rest接口。然后多刷新几次，页面就出现了。

开发人员做得真好！APP能跑起来也是很开心了。

**Comment by lulinglingcufe** [comment]
我一开始也是遇到这样的情况。感觉主要先确保 http://localhost:3000/explorer/  是可用的。我的情况是 composer-rest-server cli 工具都已经在服务器上部署过，直接启动 composer-rest-server来启动 rest接口。然后多刷新几次，页面就出现了。

开发人员做得真好！APP能跑起来也是很开心了。

**Comment by lulinglingcufe** [comment]
Please read the shell script carefully, and follow it. https://github.com/hyperledger/composer-sample-applications/blob/master/packages/letters-of-credit/installer/install.sh 

Make sure rest api provide urls like this  http://yourip:3000/api/Approve

![default](https://user-images.githubusercontent.com/17868127/43625841-b1d42c82-9721-11e8-9334-6cb595bcc225.png)

Or you can check your loading page to see which url your browser failed to get.

![default](https://user-images.githubusercontent.com/17868127/43626007-7d7737ee-9722-11e8-8f24-b30f7394993d.png)

**Comment by davidkel** [comment]
Closing as no further entries from reporter. Assume resolved.
