### ISSUE TITLE
How to call composer's rest api using react？

### ISSUE THREAD

**Issue by Messi-Q** [hyperledger/composer-sample-applications#153]
In the case of letters of credits, you can run the demo directly with the install.sh command. How do you implement the response to call the rest api?

**Comment by davidkel** [comment]
The source is available in this repository so you can inspect the code to see how it works. axios is used to send a requests to a rest server, for example.
https://github.com/hyperledger/composer-sample-applications/blob/f40b78da35d2614d2e2932c21adb63520d3311f6/packages/letters-of-credit/src/components/LetterOfCredit/LetterOfCredit.js#L75
