### ISSUE TITLE
Letter of Credit Playground

### ISSUE THREAD

**Issue by ryanyduan** [hyperledger/composer-sample-applications#156]
Model and Logic playground isn't opening for me
main.844009629eddb0254343.bundle.js:2 Uncaught SyntaxError: Unexpected identifier

**Comment by davidkel** [comment]
Need to ensure you clear your browser cache, I recommend using incognito mode in chrome. Also there was an issue with the online playground giving similar errors due to problems with the cloud provider.
This would not have been specific to Letter of Credit sample.
