### ISSUE TITLE
npm install fails for non-localhost docker

### ISSUE THREAD

**Issue by mhart** [hyperledger/composer-sample-applications#3]
If you don't have docker running directly on `localhost` (eg if you're communicating with a virtual machine, using [docker-machine](https://docs.docker.com/machine/overview/), etc) then the `npm install` step will just wait infinitely at the `while ! nc localhost 7051 </dev/null; do sleep 1; done` step.

If those references are changed, the following error will occur later in the install process:

```
...
Written Business Network Definition Archive file to digitalPropertyNetwork.zip
Command completed successfully.
Deploying business network from archive digitalPropertyNetwork.zip
Business network definition:
	Identifier: digitalproperty-network@0.0.1
	Description: Digital Property Network
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (/home/fabric-sample-applications/packages/getting-started/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._readsDone (/home/github/fabric-sample-applications/packages/getting-started/node_modules/grpc/src/node/src/client.js:158:8)
    at readCallback (/home/github/fabric-sample-applications/packages/getting-started/node_modules/grpc/src/node/src/client.js:217:12)
```

There doesn't appear to be any way around this via configuration as it's hardcoded in a number of places, but here's how to get it to work:

1. replace the three instances of `localhost` with your docker host IP (eg, `192.168.99.100`) in `scripts/start-hyperledger.sh`
1. remove/comment out the `rm -rf ~/.composer-connection-profiles/defaultProfile/*` line in `scripts/download-hyperledger.sh`
1. create a `~/.composer-connection-profiles/defaultProfile/connection.json` file with the following content, replacing `<DOCKER_IP>` with your docker host IP (eg, `192.168.99.100`) and `<HOME_DIR>` with the absolute path to your home directory (eg, `/Users/michael`):

```json
{
  "type": "hlf",
  "membershipServicesURL": "grpc://<DOCKER_IP>:7054",
  "peerURL": "grpc://<DOCKER_IP>:7051",
  "eventHubURL": "grpc://<DOCKER_IP>:7053",
  "keyValStore": "<HOME_DIR>/.composer-credentials",
  "deployWaitTime": "300",
  "invokeWaitTime": "100"
}
```

Now `npm install` (and a subsequent `npm test`) should succeed.

Not sure whether this should be documented, or the startup scripts modified to accept an env variable of some sort – but if anyone else runs into it, hopefully they'll see this issue.

**Comment by PRRemon** [comment]
Hi, I am using aws ubuntu 16.04 instance for installing hyperledger ccomposer. I tried to make changes as your suggestion. But I am unable to run npm install command successfully. 

Please find attached files for the changes I've made.

**Comment by PRRemon** [comment]
[Compser_files.zip](https://github.com/hyperledger/composer-sample-applications/files/1118830/Compser_files.zip)

**Comment by davidkel** [comment]
The nc check was removed as part of dropping support for HLF 0.6.
