### ISSUE TITLE
Cannot run the basic test

### ISSUE THREAD

**Issue by ibmmqmet** [hyperledger/composer-sample-applications#4]
Seems to be something fundamental missing from the instructions to get started.

``
info: [Composer-GettingStarted] Fabric Composer: Getting Started appliation
info: [Composer-GettingStarted] Adding default land titles to the asset registry
2017-02-07T10:53:39.782Z ERROR   FSConnectionProfileStore :load()                    Failed to loaded connection profile defaultProfile {"0":{"stack":["{Error}ENOENT: no such file or directory, open '/home/metaylor/.composer-connection-profiles/defaultProfile/connection.json' Error: ENOENT: no such file or directory, open '/home/metaylor/.composer-connection-profiles/defaultProfile/connection.json'","    at Error (native)"]}}$
error: [Composer-GettingStarted] Error: Failed to load connection profile defaultProfile
Command failed.
``

Ignoring the mis-spelled "appliation"... it then appeared to be looking for a config file that has not been created. 

I found a sample connection.json file and then got

`` 
info: [Composer-GettingStarted] Fabric Composer: Getting Started appliation
info: [Composer-GettingStarted] Adding default land titles to the asset registry
 error: [Composer-GettingStarted] Error: Failed to load connector module "composer-connector-hlf" for connection profile "defaultProfile"
Command failed.
``

There was also something in the prereqs-ubuntu script asking for a login to the previously unmentioned whitewater.ibm.com domain. Was that meant to then install something else?

**Comment by pards** [comment]
I am also experiencing the "Failed to load connection profile" issue, caused by the missing file.

Is there a sample connection.json?

**Comment by pards** [comment]
`node cli.js landregistry bootstrap`

`[Composer-GettingStarted] Fabric Composer: Getting Started appliation
[Composer-GettingStarted] Adding default land titles to the asset registry
2017-02-09T17:53:07.900Z ERROR   FSConnectionProfileStore :load()                    Failed to loaded connection profile defaultProfile {"0":{"stack":["{Error}ENOENT: no such file or directory, open '/home/fabric/.composer-connection-profiles/defaultProfile/connection.json' Error: ENOENT: no such file or directory, open '/home/fabric/.composer-connection-profiles/defaultProfile/connection.json'","    at Error (native)"]}}$
[Composer-GettingStarted] Error: Failed to load connection profile defaultProfile
Command failed.
`

Ubuntu 14.04.4 LTS
node: v4.6.2
npm: v4.1.2

**Comment by vrenjith** [comment]
This solves the problem `npm install composer-connector-hlf`

**Comment by mahendra-panchal** [comment]
@vrenjith : I have installed composer-connector-hlf

Still not able to test applications. 

Facing connection.json file issue.

> info: [Composer-GettingStarted] Hyperledger Composer: Getting Started application
info: [Composer-GettingStarted] Adding default land titles to the asset registry
error: [Composer-GettingStarted] Error: Failed to load connection profile hlfv1. Error was Error: ENOENT: no such file or directory, open '/root/.composer-connection-profiles/hlfv1/connection.json'
Command failed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! getting-started@1.0.0 bootstrapAssets: `node cli.js landregistry bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getting-started@1.0.0 bootstrapAssets script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-05-29T07_23_09_581Z-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by mahendra-panchal** [comment]
We have to create connection.json file manually.

https://hyperledger.github.io/composer/reference/connectionprofile.html

**Comment by davidkel** [comment]
I don't believe this is an issue any more. If there is still a problem could you create a new issue rather than re-opening this one as lots have changed in this repo since this was reported.
