### ISSUE TITLE
Error: EACCES: permission denied, open 'vehicle-lifecycle-network.bna' when running install.sh

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer-sample-applications#59]
When running cat installers/hlfv1/install.sh | bash from within the vehicle-lifecycle package
the operation fails with 
 Error: EACCES: permission denied, open 'vehicle-lifecycle-network.bna'

docker run --rm --network composer_default -v $(pwd)/vehicle-lifecycle-network.bna:/home/composer/vehicle-lifecycle-network.bna -v $(pwd)/.composer-connection-profiles:/home/composer/.composer-connection-profiles -v $(pwd)/.hfc-key-store:/home/composer/.hfc-key-store hyperledger/composer-cli ls -lart / /home /home/composer
returns:

total 32
-rw-------    1 node     node         29455 Jun 29 20:19 vehicle-lifecycle-network.bna
drwx------    3 node     node            19 Jun 29 21:56 .composer-connection-profiles
drwxrwxrwx    2 node     node           176 Jun 29 21:56 .hfc-key-store
drwxr-xr-x    5 root     root            22 Jun 29 21:57 ..
drwxr-sr-x    4 composer nogroup        102 Jun 29 21:57 .

/home:
total 0
drwxr-sr-x    2 node     node             6 Jun  8 16:33 node
drwxr-sr-x    4 composer nogroup        102 Jun 29 21:57 composer
drwxr-xr-x   47 root     root            78 Jun 29 21:57 ..
drwxr-xr-x    5 root     root            22 Jun 29 21:57 .

/:
total 4
drwxr-xr-x    2 root     root             6 May 25 15:18 srv
drwxr-xr-x    2 root     root          4096 May 25 15:18 sbin
drwxr-xr-x    2 root     root             6 May 25 15:18 run
drwxr-xr-x    2 root     root             6 May 25 15:18 mnt
drwxr-xr-x    5 root     root            44 May 25 15:18 media
lrwxrwxrwx    1 root     root            12 May 25 15:18 linuxrc -> /bin/busybox
drwxr-xr-x    3 root     root            18 Jun  8 16:44 opt
drwxr-xr-x    2 root     root            17 Jun  8 16:44 bin
drwxr-xr-x    8 root     root           161 Jun 22 11:25 lib
drwxrwxrwt    3 root     root            29 Jun 22 11:25 tmp
drwxr-xr-x   15 root     root            19 Jun 22 11:27 var
drwxr-xr-x   22 root     root            66 Jun 22 11:27 usr
drwx------    4 root     root             6 Jun 22 11:27 root
dr-xr-xr-x   13 root     root             0 Jun 29 21:57 sys
dr-xr-xr-x  263 root     root             0 Jun 29 21:57 proc
drwxr-xr-x    5 root     root            22 Jun 29 21:57 home
drwxr-xr-x   20 root     root            66 Jun 29 21:57 etc
drwxr-xr-x    5 root     root           340 Jun 29 21:57 dev
-rwxr-xr-x    1 root     root             0 Jun 29 21:57 .dockerenv
drwxr-xr-x   47 root     root            78 Jun 29 21:57 ..
drwxr-xr-x   47 root     root            78 Jun 29 21:57 .

**Comment by sstone1** [comment]
@LarissaAuberger can you try this again by pulling down the latest changes?
