### ISSUE TITLE
Failed to save connection profile hlfv1 when running cat installers/hlfv1/install.sh

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer-sample-applications#68]
cat installers/hlfv1/install.sh 
fails with this message:
**********************************************************
composer network deploy -p hlfv1 -a vehicle-lifecycle-network.bna -i PeerAdmin -s whatever
pwd
pwd
pwd

Deploying business network from archive: vehicle-lifecycle-network.bna
Business network definition:
     Identifier: org-acme-biznet@0.1.0
     Description: Vehicle Lifecycle Network

Error: Failed to save connection profile hlfv1
**********************************************************

However, when running this command in a command line:
"composer network deploy -p hlfv1 -a vehicle-lifecycle-network.bna -i PeerAdmin -s whatever"
the archive is successfully deployed.

**Comment by mbwhite** [comment]
This looks to be an issue with the setup of installer - could you ask please in the RocketChat channel
https://chat.hyperledger.org/channel/composer
