### ISSUE TITLE
The instructions on how to deploy business network need correction

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer-sample-applications#72]
These instructions on how to deploy a business network need correction:
https://github.com/hyperledger/composer-sample-applications/blob/master/packages/digitalproperty-app/README.md

For hlfv1 "npm run deployNetwork" fails.

/root/.npm/_logs/2017-07-20T21_46_01_629Z-debug.log" indicates that "composer network deploy ***" command failed

Manual execution of 
composer network deploy -p hlfv1 --archiveFile digitalPropertyNetwork.bna  --enrollId admin --enrollSecret adminpw 

leads to 
[InvalidArgumentException]
  Command "network" is not defined.

**Comment by davidkel** [comment]
That looks like composer-cli was not installed but something else that is called composer

**Comment by davidkel** [comment]
Closing issue as appears to be resolved.
