### ISSUE TITLE
"npm install" leads to "npm ERR! code EINTEGRITY"

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer-sample-applications#98]
I performed
 git clone https://github.com/hyperledger/composer-sample-applications.git
cd composer-sample-applications
npm install

and see errors. This is the complete message:

lerna info version 2.4.0
lerna info Bootstrapping 5 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm WARN deprecated @ionic/cli-plugin-cordova@1.0.0: Ionic CLI 3.8 no longer loads this plugin. See https://github.co                                                                   m/ionic-team/ionic-cli/blob/master/CHANGELOG.md#3.8.0
lerna ERR! npm WARN deprecated babili@0.0.10: babili has been renamed to babel-minify. Please update to babel-minify
lerna ERR! npm WARN deprecated babel-preset-babili@0.0.10: babili has been renamed to babel-minify. Please update to babel-prese                                                                   t-minify
lerna ERR! npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
lerna ERR! npm WARN vehicle-lifecycle-car-builder No repository field.
lerna ERR! npm WARN vehicle-lifecycle-car-builder No license field.
lerna ERR!
lerna ERR! npm ERR! code EINTEGRITY
lerna ERR! npm ERR! sha1-NbLUDNNRNa7OxL5llTIUj1rGfaY= integrity checksum failed when using sha1: wanted sha1-NbLUDNNRNa7OxL5llTI                                                                   Uj1rGfaY= but got sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=. (0 bytes)
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/evaluator.spec.js'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/index_writer_spec.js'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/bundler_spec.js'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/symbols.spec.js'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/test_support.js'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/tsc.spec.js'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/typescript.mocks.js'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/index_writer_spec.d.ts'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/collector.spec.d.ts'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/index_writer_spec.js.map'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/main.spec.d.ts'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/bundler_spec.d.ts'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/main.spec.js.map'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/symbols.spec.d.ts'
lerna ERR! npm WARN tar ENOENT: no such file or directory, open '/home/ehtest/github/composer-sample-applications/packages/vehic                                                                   le-lifecycle-car-builder/node_modules/.staging/@angular/tsc-wrapped-c73bea6f/test/collector.spec.js.map'
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /home/ehtest/.npm/_logs/2017-10-18T09_29_33_207Z-debug.log
lerna ERR!

Indeed, ~/github/composer-sample-applications/packages/vehicle-lifecycle/node_modules
only contains vehicle-lifecycle-model/ and vehicle-lifecycle-network/
There is no .staging directory in it.

**Comment by davidkel** [comment]
Just tried this and don't get this error. I suspect there is some problem with the npm repository when you tried. Could you try again. If you still get an error could you provide details on your node level, npm level, whether you are running native or in a VM and if a VM are you sharing file systems in anyway ?

**Comment by davidkel** [comment]
Closing as I believe Larissa has got this working now.

**Comment by simran-git** [comment]
What was the fix? I am getting same error
